service: php-websocket-bref

provider:
    name: aws
    region: ap-northeast-1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:DeleteItem
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:UpdateItem
          - execute-api:ManageConnections
        Resource: "*"

functions:
  websocket:
    handler: src/index.php
    runtime: php-84
    timeout: 900
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: message

resources:
  Resources:
    WebSocketConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: WebSocketConnections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - ./vendor/bref/bref

package:
  individually: true
  include:
    - vendor/**
    - src/**
